{
  "formatVersion": "1.1",
  "component": {
    "group": "top.aenp.mwl",
    "module": "MythicWorldLib",
    "version": "26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MythicWorldLib-26.1.jar",
          "url": "MythicWorldLib-26.1.jar",
          "size": 35525,
          "sha512": "2af60f6d409a7b6e73993b1cb79a4367d47c3e71e0be1d365731a827596b097b07f633fe4c604a7772a171f6c9714ff82862d00ee854601ff4ff64737c322107",
          "sha256": "e69639cdaba6b95188930173236aa4c915deaa705fa75207a14c9510bb7accdb",
          "sha1": "28da08795f373a40e364a5e8861de5a68a881daa",
          "md5": "cc6385886d967a4e2d9239e12cdff3c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.17+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "MythicWorldLib-26.1.jar",
          "url": "MythicWorldLib-26.1.jar",
          "size": 35525,
          "sha512": "2af60f6d409a7b6e73993b1cb79a4367d47c3e71e0be1d365731a827596b097b07f633fe4c604a7772a171f6c9714ff82862d00ee854601ff4ff64737c322107",
          "sha256": "e69639cdaba6b95188930173236aa4c915deaa705fa75207a14c9510bb7accdb",
          "sha1": "28da08795f373a40e364a5e8861de5a68a881daa",
          "md5": "cc6385886d967a4e2d9239e12cdff3c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MythicWorldLib-26.1-sources.jar",
          "url": "MythicWorldLib-26.1-sources.jar",
          "size": 24432,
          "sha512": "6135df8eea4d1b97aa1feafc2b6df654434fce40a05e835d728db5ce03f079cf6f2a62df85de2aaeb73c5a6b940b68169fea01b73d311454024906fc7efc09c2",
          "sha256": "6982ee2c8c98be43aab67bc1056aa14e0919dd559964f52360a261928f60e68a",
          "sha1": "9dff567ce817eb48496039b2ab0a4c48180abd5d",
          "md5": "d7dbc242826b43b8ec35cb36ae09c0b4"
        }
      ]
    }
  ]
}
