{
  "formatVersion": "1.1",
  "component": {
    "group": "top.aenp.mwl",
    "module": "MythicWorldLib",
    "version": "26.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MythicWorldLib-26.1.1.jar",
          "url": "MythicWorldLib-26.1.1.jar",
          "size": 44247,
          "sha512": "405ef8d0686f881e3a94553c4275f9e0a677ffcc0277d06e2e191e2cd6054c832dc7784329b88332ecd42f6e789475b44028da197522ca25e0c48147910015b5",
          "sha256": "b6534603895c96fba3630925b5997fba950816eaf2f6ab57de2de81e56f68849",
          "sha1": "793861a7f67adaa55efed16bafb2e491859f20a5",
          "md5": "deb1dd6321af97f7545c08088bed4ca7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.17+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "MythicWorldLib-26.1.1.jar",
          "url": "MythicWorldLib-26.1.1.jar",
          "size": 44247,
          "sha512": "405ef8d0686f881e3a94553c4275f9e0a677ffcc0277d06e2e191e2cd6054c832dc7784329b88332ecd42f6e789475b44028da197522ca25e0c48147910015b5",
          "sha256": "b6534603895c96fba3630925b5997fba950816eaf2f6ab57de2de81e56f68849",
          "sha1": "793861a7f67adaa55efed16bafb2e491859f20a5",
          "md5": "deb1dd6321af97f7545c08088bed4ca7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MythicWorldLib-26.1.1-sources.jar",
          "url": "MythicWorldLib-26.1.1-sources.jar",
          "size": 25716,
          "sha512": "538a47fd7547e33854b207ec8a2ba98c6230618d4d56fdc60241928bcd1a52ea65adca1a581fc9a697b8d4670e910ccd96be8cd315a0a22547e8e912e9ae84f6",
          "sha256": "6d3d11de7e22136aa888e3fdaccbdfdf7213aa0e23b19c0cacf9c48d0e70113a",
          "sha1": "52acdcc38aa606624e1aaca2ebd48f980d267e39",
          "md5": "b37b097c2b089ed9ce0b8b64ee58f87d"
        }
      ]
    }
  ]
}
